import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Nav from "./components/Nav";
import { Cairo } from "next/font/google";
import Footer from "./components/Footer";

const cairo = Cairo({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${cairo.className} relative`}>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
